== Running Taco Cloud

Starting with Chapter 6, Taco Cloud is broken into a multi-module Maven project. To build the full project, use `mvnw` (the Maven wrapper) at the command line like this:

[source,sh]
----
% ./mvnw clean package
----

The Maven build will also build the Angular client code and package it along with the Spring code. To do that, you'll need to make sure that you have Node and the Angular CLI installed before building the project. (See https://cli.angular.io/ for details.)

Once the project is built, you can run the executable JAR file from the `tacos` project:

[source,sh]
----
% java -jar tacos/target/taco-cloud-0.0.6-SNAPSHOT.jar
----

Once the application has started, open your web browser and navigate to http://localhost:8080 to see the Taco Cloud home page.

== Taco Cloud modules

The multi-module Maven project is made up of the following modules:

 - `tacocloud-api` : The REST API
 - `tacocloud-data` : The persistence module
 - `tacocloud-domain` : The domain types
 - `tacocloud-security` : The security module (TODO: Not fully functional yet.)
 - `tacocloud-ui` : A Typescript Angular UI
 - `tacocloud-web` : The web module (largely leftovers from previous chapters. TODO: Clean up and remove.)
 - `tacos` : The main module that pulls the other modules together and provides the Spring Boot main class.
