spring:
  thymeleaf:
    cache: false
    
server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:mykeys.jks
    key-store-password: changeit
    key-store-type: JKS
    key-store-provider: SUN
    key-alias: tomcat
    
taco:
  orders:
    pageSize: 4
 