INSERT INTO USER (ID, CITY, FULLNAME, PASSWORD, PHONE_NUMBER, STATE, STREET, USERNAME, ZIP) VALUES (1, 'example', 'rmartins', '$2a$10$fb8UmzfA83o01LGD7WanueywC7ZktSYxTxQp5qoz4n5/aWqSKLrka', 'example', 'example', 'example', 'rmartins', 'example');

INSERT INTO INGREDIENT (ID, NAME, TYPE) VALUES ('FLTO', 'Flour Tortilla', 0);
INSERT INTO INGREDIENT (ID, NAME, TYPE) VALUES ('COTO', 'Corn Tortilla', 0);
INSERT INTO INGREDIENT (ID, NAME, TYPE) VALUES ('GRBF', 'Ground Beef', 1);
INSERT INTO INGREDIENT (ID, NAME, TYPE) VALUES ('CARN', 'Carnitas', 1);
INSERT INTO INGREDIENT (ID, NAME, TYPE) VALUES ('TMTO', 'Diced Tomatoes', 2);
INSERT INTO INGREDIENT (ID, NAME, TYPE) VALUES ('LETC', 'Lettuce', 2);
INSERT INTO INGREDIENT (ID, NAME, TYPE) VALUES ('CHED', 'Cheddar', 3);
INSERT INTO INGREDIENT (ID, NAME, TYPE) VALUES ('JACK', 'Monterrey Jack', 3);
INSERT INTO INGREDIENT (ID, NAME, TYPE) VALUES ('SLSA', 'Salsa', 4);
INSERT INTO INGREDIENT (ID, NAME, TYPE) VALUES ('SRCR', 'Sour Cream', 4);